rule all:
    input:  finished=expand("montecarlo/finished_n_100_ss_{ss}", ss=[3, 4, 5, 10, 15, 20, 25, 30, 50, 75])

rule ds:
  threads: 1
  resources: mem='8G',time='04:00:00'
  output: "{dir}/finished_n_{n}_ss_{ss}"
  shell: "./montecarlo.R {wildcards.n} {wildcards.ss} covar.rds counts.rds {wildcards.dir}"

